name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Run build on Master push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Give permission to run script
        run: chmod +x ./build_prod.sh

      - name: Run build
        run: ./build_prod.sh

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Bun dependencies
        run: bun install

      - name: Start local db
        run: bun run db:push

      - name: Start Bun app (background)
        run: bun run dev &
        env:
          PORT: 3000

      - name: Run Cypress tests
        run: bunx cypress run

  coverage:
    name: TypeScript Coverage
    runs-on: ubuntu-latest
    needs: e2e

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Init test db
        run: bun run db:push:test

      - name: Run tests
        run: bun run test

      - name: Run test Coverage
        run: bun run test:coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: [build, e2e, coverage]

    steps:
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}