name: E2E Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Bun dependencies
        run: bun install

      - name: Start local db
        run: bun run db:push

      - name: Start Bun app (background)
        run: bun run dev &
        env:
          PORT: 3000

      - name: Run Cypress tests
        run: bunx cypress run
