name: TypeScript Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run TypeScript Coverage
        run: bun run ts-coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: ts-coverage-report
          path: coverage-ts/*.html
